void gsac_set_param_lp(int ncmd, char **cmdstr);
void gsac_exec_lp(void);
void gsac_set_param_hp(int ncmd, char **cmdstr);
void gsac_exec_hp(void);
void gsac_set_param_bp(int ncmd, char **cmdstr);
void gsac_exec_bp(void);
void gsac_set_param_br(int ncmd, char **cmdstr);
void gsac_exec_br(void);
void gsac_set_param_in(int ncmd, char **cmdstr);
void gsac_exec_in(void);
void gsac_set_param_nop(int ncmd, char **cmdstr);
void gsac_exec_nop(void);
void gsac_set_param_read(int ncmd, char **cmdstr);
void gsac_exec_read(void);
void gsac_set_param_write(int ncmd, char **cmdstr);
void gsac_exec_write(void);
void gsac_set_param_plot(int ncmd, char **cmdstr);
void gsac_exec_plot(void);
void gsac_set_param_plotctl(int ncmd, char **cmdstr);
void gsac_exec_plotctl(void);
void gsac_set_param_plotpk(int ncmd, char **cmdstr);
void gsac_exec_plotpk(void);
void gsac_set_param_plotsp(int ncmd, char **cmdstr);
void gsac_exec_plotsp(void);
void gsac_set_param_lh(int ncmd, char **cmdstr);
void gsac_exec_lh(void);
void gsac_help(int ncmd, char **cmdstr, char **helper);
void gsac_set_param_rtr(int ncmd, char **cmdstr);
void gsac_exec_rtr(void);
void gsac_set_param_rtr(int ncmd, char **cmdstr);
void gsac_exec_rtr(void);
void gsac_set_param_rmean(int ncmd, char **cmdstr);
void gsac_exec_rmean(void);
void gsac_set_param_bg(int ncmd, char **cmdstr);
void gsac_exec_bg(void);
void gsac_set_param_add(int ncmd, char **cmdstr);
void gsac_exec_add(void);
void gsac_set_param_sub(int ncmd, char **cmdstr);
void gsac_exec_sub(void);
void gsac_set_param_mul(int ncmd, char **cmdstr);
void gsac_exec_mul(void);
void gsac_set_param_div(int ncmd, char **cmdstr);
void gsac_exec_div(void);
void gsac_set_param_int(int ncmd, char **cmdstr);
void gsac_exec_int(void);
void gsac_set_param_dif(int ncmd, char **cmdstr);
void gsac_exec_dif(void);
void gsac_set_param_fft(int ncmd, char **cmdstr);
void gsac_exec_fft(void);
void gsac_set_param_ch(int ncmd, char **cmdstr);
void gsac_exec_ch(void);
void gsac_set_param_sort(int ncmd, char **cmdstr);
void gsac_exec_sort(void);
void gsac_set_param_del(int ncmd, char **cmdstr);
void gsac_exec_del(void);
void gsac_set_param_sync(int ncmd, char **cmdstr);
void gsac_exec_sync(void);
void gsac_set_param_wh(int ncmd, char **cmdstr);
void gsac_exec_wh(void);
void gsac_set_param_color(int ncmd, char **cmdstr);
void gsac_exec_color(void);
void gsac_set_param_fg(int ncmd, char **cmdstr);
void gsac_exec_fg(void);
void gsac_set_param_cuterr(int ncmd, char **cmdstr);
void gsac_exec_cuterr(void);
void gsac_set_param_rot(int ncmd, char **cmdstr);
void gsac_exec_rot(void);
void gsac_set_param_cut(int ncmd, char **cmdstr);
void gsac_exec_cut(void);
void gsac_set_param_trans(int ncmd, char **cmdstr);
void gsac_exec_trans(void);
void gsac_set_param_cd(int ncmd, char **cmdstr);
void gsac_exec_cd(void);
void gsac_set_param_filter(int ncmd, char **cmdstr);
void gsac_exec_filter(void);
void gsac_set_param_hilb(int ncmd, char **cmdstr);
void gsac_exec_hilb(void);
void gsac_set_param_env(int ncmd, char **cmdstr);
void gsac_exec_env(void);
void gsac_set_param_math(int ncmd, char **cmdstr);
void gsac_exec_math(void);
void gsac_set_param_qdp(int ncmd, char **cmdstr);
void gsac_exec_qdp(void);
void gsac_set_param_prs(int ncmd, char **cmdstr);
void gsac_exec_prs(void);
void gsac_set_param_merge(int ncmd, char **cmdstr);
void gsac_exec_merge(void);
void gsac_set_param_ylim(int ncmd, char **cmdstr);
void gsac_exec_ylim(void);
void gsac_set_param_dagc(int ncmd, char **cmdstr);
void gsac_exec_dagc(void);
void gsac_set_param_pctl(int ncmd, char **cmdstr);
void gsac_exec_pctl(void);
void gsac_set_param_hold(int ncmd, char **cmdstr);
void gsac_exec_hold(void);
void gsac_set_param_pause(int ncmd, char **cmdstr);
void gsac_exec_pause(void);
void gsac_set_param_echo(int ncmd, char **cmdstr);
void gsac_exec_echo(void);
void gsac_set_param_xlim(int ncmd, char **cmdstr);
void gsac_exec_xlim(void);
void gsac_set_param_rot3(int ncmd, char **cmdstr);
void gsac_exec_rot3(void);
void gsac_set_param_sgn(int ncmd, char **cmdstr);
void gsac_exec_sgn(void);
void gsac_set_param_conv(int ncmd, char **cmdstr);
void gsac_exec_conv(void);
void gsac_set_param_corr(int ncmd, char **cmdstr);
void gsac_exec_corr(void);
void gsac_set_param_stack(int ncmd, char **cmdstr);
void gsac_exec_stack(void);
void gsac_set_param_rev(int ncmd, char **cmdstr);
void gsac_exec_rev(void);
void gsac_set_param_markt(int ncmd, char **cmdstr);
void gsac_exec_markt(void);
void gsac_set_param_taper(int ncmd, char **cmdstr);
void gsac_exec_taper(void);
void gsac_set_param_hist(int ncmd, char **cmdstr);
void gsac_exec_hist(void);
void gsac_set_param_whit(int ncmd, char **cmdstr);
void gsac_exec_whit(void);
void gsac_set_param_fileid(int ncmd, char **cmdstr);
void gsac_exec_fileid(void);
void gsac_set_param_smth(int ncmd, char **cmdstr);
void gsac_exec_smth(void);
void gsac_set_param_refr(int ncmd, char **cmdstr);
void gsac_exec_refr(void);
void gsac_set_param_mulf(int ncmd, char **cmdstr);
void gsac_exec_mulf(void);
void gsac_set_param_divf(int ncmd, char **cmdstr);
void gsac_exec_divf(void);
void gsac_set_param_addf(int ncmd, char **cmdstr);
void gsac_exec_addf(void);
void gsac_set_param_subf(int ncmd, char **cmdstr);
void gsac_exec_subf(void);
void gsac_set_param_writesp(int ncmd, char **cmdstr);
void gsac_exec_writesp(void);
void gsac_set_param_dec(int ncmd, char **cmdstr);
void gsac_exec_dec(void);
void gsac_set_param_map(int ncmd, char **cmdstr);
void gsac_exec_map(void);
void gsac_set_param_triangle(int ncmd, char **cmdstr);
void gsac_exec_triangle(void);
void gsac_set_param_boxcar(int ncmd, char **cmdstr);
void gsac_exec_boxcar(void);
void gsac_set_param_trapezoid(int ncmd, char **cmdstr);
void gsac_exec_trapezoid(void);
void gsac_set_param_v(int ncmd, char **cmdstr);
void gsac_exec_v(void);
void gsac_set_param_xgrid(int ncmd, char **cmdstr);
void gsac_exec_xgrid(void);
void gsac_set_param_ygrid(int ncmd, char **cmdstr);
void gsac_exec_ygrid(void);
void gsac_set_param_grid(int ncmd, char **cmdstr);
void gsac_exec_grid(void);
void gsac_set_param_back(int ncmd, char **cmdstr);
void gsac_exec_back(void);
void gsac_set_param_outcsv(int ncmd, char **cmdstr);
void gsac_exec_outcsv(void);
void gsac_set_param_rh(int ncmd, char **cmdstr);
void gsac_exec_rh(void);
void gsac_set_param_title(int ncmd, char **cmdstr);
void gsac_exec_title(void);
void gsac_set_param_mt(int ncmd, char **cmdstr);
void gsac_exec_mt(void);
void gsac_set_param_shift(int ncmd, char **cmdstr);
void gsac_exec_shift(void);
void gsac_set_param_ricker(int ncmd, char **cmdstr);
void gsac_exec_ricker(void);
